services:
  playground:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - eopa

  eopa:
    image: ${EOPA_IMAGE:-ghcr.io/styrainc/enterprise-opa:edge}
    pull_policy: ${EOPA_PULL_POLICY:-always}
    ports:
      - "8181:8181"
    command:
      - run
      - --server
      - --addr=:8181
      - --log-level=debug
      - --no-license-fallback
    environment:
      EOPA_LICENSE_KEY: ${EOPA_LICENSE_KEY:-}
